import { ThemeProvider } from '@/components/providers/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { ChildProps } from '@/types'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Montserrat, Space_Grotesk as SpaceGrotesk } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import './globals.css'

const spaceGrotesk = SpaceGrotesk({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
	variable: '--font-space-grotesk',
})

const montserrat = Montserrat({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	variable: '--font-montserrat',
})

export const metadata: Metadata = {
	title: 'Note - List',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: ChildProps) {
	return (
		<ClerkProvider>
			<html lang='en' suppressHydrationWarning>
				<body
					className={`${montserrat.variable} ${spaceGrotesk.variable} custom-scrollbar overflow-x-hidden`}
				>
					<ThemeProvider
						attribute='class'
						defaultTheme='dark'
						enableSystem
						disableTransitionOnChange
					>
						<NextTopLoader
							color='#c65f06'
							initialPosition={0.08}
							crawlSpeed={200}
							height={2}
							crawl={true}
							showSpinner={false}
							easing='ease'
							speed={200}
							shadow='0 0 10px #c65f06,0 0 5px #c65f06'
							zIndex={1600}
							showAtBottom={false}
						/>
						<Toaster />
						{children}
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
